### ISSUE TITLE
Problem BilateralCS

### ISSUE THREAD

**Issue by ZenpatFR** [LordOfLunacy/Insane-Shaders#2]
Hi, sorry to bother you, try to solve a little problem, i use your BilateralCS effect with reshade in AC (21:9), in game i've few transparent white rectangle on left border, to solve  the problem i need to disable bilateralCS.fx , any idea ? All preset with BilateralCS have this problem, i can use other sharper effect, but bilateral is always better...  see screenshoots here :  https://postimg.cc/gallery/RqH59Pf

**Comment by B-eT-a** [comment]
does this also happen in other resolutions and aspect ratios?
can you test 16:9 too?

**Comment by ZenpatFR** [comment]
hi, in 1920x1080 and 2560x1440 i don't have this problem. And a friend with real 4k screen 3840x2560 don t have problem... then 21:9 is the problem yes

**Comment by ZenpatFR** [comment]
Sorry closed by error

**Comment by LordOfLunacy** [comment]
[ Fix](https://github.com/LordOfLunacy/Insane-Shaders/commit/ba79ca33e2aa49ae18cfa26cce9bdda69b5595ed)

Fixed the issue, turns out that there were race conditions at any resolution that had a width that was not a multiple of 128. This automatically excluded most 16:9 resolutions, hence why the bug went unnoticed.

**Comment by ZenpatFR** [comment]
Thank you,  work perfect !!
